# Travis CI configuration

language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - COMPOSER_FLAGS="--prefer-stable"
  - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - travis_retry composer dump-autoload

script:
  - php vendor/bin/phpunit
